PortalFibrobeton/Controllers/Cnc/CncHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PortalFibrobeton.Models.Entity;

namespace PortalFibrobeton.Controllers.Cnc
{
    public class CncHomeController : Controller
    {
        cncEntities dbCnc = new cncEntities();

        // GET: CncHome
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HomePageCnc()
        {

            var query = from a in dbCnc.tuketim_degerleri.SqlQuery("SELECT * FROM tuketim_degerleri order by ID DESC").ToList()
                        select a;

            return View(query);
        }

        public ActionResult Deneme()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GecmisKayitEkleme()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GecmisKayitEkleme(CNC_1 p1, DateTime tarih, double ms, string makine)
        {
            try
            {
                
                p1.tarih = tarih.AddDays(1).AddHours(7).AddMinutes(59).AddSeconds(2);
                var filtreTarihBas = tarih.AddDays(1);
                var filtreTarihBit = filtreTarihBas.AddDays(1);

                //İlgili gündeki son kayıtları silme
                var eskiKayitlar = dbCnc.CNC_1.Where(a => a.tarih >= filtreTarihBas && a.tarih < filtreTarihBit && a.makine_adi == makine).ToList();
                foreach(var item in eskiKayitlar)
                {
                    dbCnc.CNC_1.Remove(item);
                };

                //Yeni veri kayıt ekleme
                p1.makine_adi = makine;
                p1.calisma_saati = ms;
                dbCnc.CNC_1.Add(p1);
                dbCnc.SaveChanges();

                TempData["successAdd"] = "Kayıt ekleme başarılı!";
            }
            catch(Exception)
            {
                TempData["errorAdd"] = "Kayıt ekleme sırasında hata oluştu!";
            }
            

            return View();
        }
    }
}

PortalFibrobeton/Views/CncHome/Deneme.cshtml
@{
    ViewBag.Title = "Deneme";
    Layout = "~/Views/Shared/CncLayout.cshtml";
}

<head>
    <meta charset="utf-8">

    <title>Tooltip examples</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
    @*<link rel="stylesheet" href="node_modules/chartist/dist/chartist.min.css">*@
    @*<script src="~/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js"></script>*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    @*<script src="~/Scripts/chartist-plugin-pointlabels.js"></script>*@
    <link href="~/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css" rel="stylesheet" />
    <script src="~/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.js"></script>
    <script src="~/chartist-plugin-tooltip-master/src/scripts/chartist-plugin-tooltip.js"></script>
    <link href="~/chartist-plugin-tooltip-master/src/css/chartist-plugin-tooltip.css" rel="stylesheet" />

    <style>
        .ct-chart {
            position: relative;
        }

        .ct-tooltip {
            position: absolute;
            display: inline-block;
            min-width: 5em;
            padding: 8px 10px;
            background: #383838;
            color: #fff;
            text-align: center;
            pointer-events: none;
            z-index: 100;
            transition: opacity .2s linear;
        }

            .ct-tooltip:before {
                position: absolute;
                bottom: -14px;
                left: 50%;
                border: solid transparent;
                content: ' ';
                height: 0;
                width: 0;
                pointer-events: none;
                border-color: rgba(251, 249, 228, 0);
                border-top-color: #383838;
                border-width: 7px;
                margin-left: -8px;
            }

            .ct-tooltip.hide {
                display: block;
                opacity: 0;
                visibility: hidden;
            }
    </style>
</head>
<body>
    <div class="card">
        <div class="col-lg-12">
            <div class="ct-chart ct-chart-line"></div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card">
            <div class="test"></div>
        </div>
    </div>

    <div class="ct-chart ct-chart-pie"></div>
    <div class="ct-chart ct-chart-bar"></div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="node_modules/chartist/dist/chartist.min.js"></script>
    @*<script src="chartist-plugin-tooltip.js"></script>*@





    <script>
        (function (root, factory) {
            if (typeof define === 'function' && define.amd) {
                // AMD. Register as an anonymous module.
                define(['chartist', 'jquery'], function (chartist, jquery) {
                    return (root.returnExportsGlobal = factory(chartist, jquery));
                });
            } else if (typeof exports === 'object') {
                // Node. Does not work with strict CommonJS, but
                // only CommonJS-like enviroments that support module.exports,
                // like Node.
                module.exports = factory(require('chartist'), require('jquery'));
            } else {
                root['Chartist.plugins.tooltip'] = factory(root.chartist, root.jquery);
            }
        }(this, function (Chartist, $) {

            /**
             * This Chartist tooltip plugin is a modified version of
             * https://github.com/Globegitter/chartist-plugin-tooltip.
             *
             */
            'use strict';

            var defaultOptions = {
                valueTransform: Chartist.noop,
                seriesName: true // Show name of series in tooltip.
            };

            Chartist.plugins = Chartist.plugins || {};

            Chartist.plugins.tooltip = function (options) {

                options = Chartist.extend({}, defaultOptions, options);

                return function tooltip(chart) {

                    var tooltipSelector = '.ct-point';
                    if (chart instanceof Chartist.Bar) {
                        tooltipSelector = '.ct-bar';
                    } else if (chart instanceof Chartist.Pie) {
                        tooltipSelector = '[class^=ct-slice]';
                    }

                    var $chart = $(chart.container),
                        $toolTip = $chart
                            .append('<div class="ct-tooltip"></div>')
                            .find('.ct-tooltip')
                            .hide();

                    $chart.on('mouseenter', tooltipSelector, function () {
                        var $point = $(this),
                            seriesName = $point.parent().attr('ct:series-name'),
                            tooltipText = '';

                        if (options.seriesName && seriesName) {
                            tooltipText += seriesName + '<br>';
                        }

                        if ($point.attr('ct:meta')) {
                            tooltipText += $point.attr('ct:meta') + '<br>';
                        }

                        var value = $point.attr('ct:value') || '0';

                        tooltipText += options.valueTransform(value);

                        $toolTip.html(tooltipText).show();
                    });

                    $chart.on('mouseleave', tooltipSelector, function () {
                        $toolTip.hide();
                    });

                    $chart.on('mousemove', function (event) {
                        $toolTip.css({
                            left: (event.offsetX || event.originalEvent.layerX) - $toolTip.width() / 2 - 10,
                            top: (event.offsetY || event.originalEvent.layerY) - $toolTip.height() - 40
                        });
                    });

                };

            };

            return Chartist.plugins.tooltip;

        }));
    </script>

    <script src="~/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.js"></script>
    <script src="~/chartist-plugin-tooltip-master/src/scripts/chartist-plugin-tooltip.js"></script>

    <script>

        new Chartist.Line('.test', {
            labels: [1, 2, 3],
            series: [
                [
                    { meta: 'description', value: 1 },
                    { meta: 'description', value: 5 },
                    { meta: 'description', value: 3 }
                ],
                [
                    { meta: 'other description', value: 2 },
                    { meta: 'other description', value: 4 },
                    { meta: 'other description', value: 2 }
                ]
            ]
        }, {
            low: 0,
            high: 8,
            fullWidth: true,
            plugins: [
                Chartist.plugins.tooltip()
            ]
        });
    </script>


    <script>
        new Chartist.Line('.ct-chart-line', {
            labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
            series: [
                [12, 9, 7, 8, 5],
            ]
        }, {
            fullWidth: true,
            chartPadding: {
                right: 40
            },
            plugins: [
                Chartist.plugins.tooltip()
            ]
        });

        new Chartist.Pie('.ct-chart-pie', {
            series: [20, 10, 30, 40]
        }, {
            plugins: [
                Chartist.plugins.tooltip()
            ]
        });

        new Chartist.Bar('.ct-chart-bar', {
            labels: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
            series: [20, 60, 120, 200, 180, 20, 10]
        }, {
            distributeSeries: true,
            plugins: [
                Chartist.plugins.tooltip()
            ]
        });
    </script>
</body>

PortalFibrobeton/Views/CncHome/GecmisKayitEkleme.cshtml
@{
    ViewBag.Title = "GecmisKayitEkleme";
    Layout = "~/Views/Shared/CncLayout.cshtml";
}

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
</head>


@using (Html.BeginForm("GecmisKayitEkleme", "CncHome", FormMethod.Post)) 
 {


<div class="col-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Kayıt Bilgileri</h5>
                <div class="row align-items-center">
                    <div class="col-md-10">
                        <label class="m-t-20">Tarih</label>
                        <div class="input-group">
                            <input type="text" style="cursor:pointer" autocomplete="off" class="form-control datepicker" name="tarih" id="dp1" /><button class="btn disabled" style="background-color: #0094ff;border:none;color:white;cursor:default"><i class="ri-calendar-line"></i></button>
                        </div>
                    </div>
                </div>
                <div class="row align-items-center">
                    <div class="col-md-10 mt-3">
                        <label class="m-t-20">Makine Adı</label>
                        <select class="form-control" name="makine">
                            <option selected="selected"></option>
                            <option>MN01</option>
                            <option>MN02</option>
                            <option>CMA03</option>
                            <option>CMA04</option>
                            <option>CMA05</option>
                            <option>CMA06</option>
                            <option>CMA07</option>
                            <option>CMA08</option>
                        </select>
                    </div>
                </div>
                <div class="row align-items-center">
                    <div class="col-md-10 mt-3">
                        <label class="m-t-20">Çalışma Süresi (milisaniye)</label>
                        <div class="input-group">
                            <input type="text" autocomplete="off" class="form-control" name="ms" />
                        </div>
                    </div>
                </div>
                <br />
                @if (TempData["successAdd"] != null)
                {
                    <div class="alert alert-success">@TempData["successAdd"].ToString()</div>
                }
                @if (TempData["errorAdd"] != null)
                {
                    <div class="alert alert-danger">@TempData["errorAdd"].ToString()</div>
                }
                <button type="submit" style="margin-left:170px;" class="btn btn-primary">Kaydet</button>

            </div>
        </div>
    </div>
 }



<script>

    $(function ($) {
        $.fn.datepicker.dates['tr'] =
        {
            days: ["Pazar", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"],
            daysShort: ["Pz", "Pzt", "Sal", "Çrş", "Prş", "Cu", "Cts", "Pz"],
            daysMin: ["Pz", "Pzt", "Sa", "Çr", "Pr", "Cu", "Ct", "Pz"],
            months: ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
            monthsShort: ["Oca", "Şub", "Mar", "Nis", "May", "Haz", "Tem", "Ağu", "Eyl", "Eki", "Kas", "Ara"],
            today: "Bugün",
        };
    });

    $(function () {

        today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() - 1);

        $('#dp1').datepicker({
            endDate: today,
            autoclose: true,
            format: 'dd-mm-yyyy',
            language: "tr",

        })
    });
</script>